/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AssistanceNeeded = { 'no' : null } |
  { 'equinox' : null } |
  { 'onshore' : null };
export interface Case {
  'id' : bigint,
  'assistanceNeeded' : [] | [AssistanceNeeded],
  'startTime' : Time,
  'escalationTransferDestination' : [] | [Department],
  'emrCaseNumber' : [] | [string],
  'endTime' : Time,
  'caseType' : [] | [CaseType],
  'agentName' : string,
  'taskType' : TaskType,
  'notes' : string,
  'ticketStatus' : [] | [TicketStatus],
  'escalationTransferType' : [] | [EscalationTransferType],
  'caseOrigin' : [] | [CaseOrigin],
}
export type CaseOrigin = { 'chat' : null } |
  { 'email' : null } |
  { 'voiceCall' : null };
export type CaseType = { 'new' : null } |
  { 'followup' : null } |
  { 'reassigned' : null };
export type Department = { 'cas' : null } |
  { 'crm' : null } |
  { 'csm' : null } |
  { 'erx' : null } |
  { 'lab' : null } |
  { 'mat' : null } |
  { 'psa' : null } |
  { 'accounting' : null } |
  { 'emrSupport' : null } |
  { 'productEnhancement' : null } |
  { 'pdmp' : null } |
  { 'billing' : null } |
  { 'sales' : null } |
  { 'clientAdvocates' : null } |
  { 'cleanup' : null };
export type EscalationTransferType = { 'na' : null } |
  { 'escalated' : null } |
  { 'transferred' : null };
export type TaskType = { 'pod' : null } |
  { 'clientMeeting' : null } |
  { 'trainingFeedbackNewTeamMember' : null } |
  { 'clientSideTraining' : null } |
  { 'supportEMRTickets' : null } |
  { 'feedbackReview' : null } |
  { 'internalTraining' : null } |
  { 'internalTeamMeeting' : null } |
  { 'trainingNewTeamMember' : null } |
  { 'break15' : null } |
  { 'break30' : null };
export type TicketStatus = { 'new' : null } |
  { 'resolved' : null } |
  { 'pending' : null } |
  { 'escalated' : null } |
  { 'open' : null } |
  { 'transferred' : null } |
  { 'onHold' : null };
export type Time = bigint;
export interface UserProfile {
  'username' : string,
  'shiftPreferences' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'batchCreateCases' : ActorMethod<
    [
      Array<
        {
          'assistanceNeeded' : [] | [AssistanceNeeded],
          'startTime' : Time,
          'escalationTransferDestination' : [] | [Department],
          'emrCaseNumber' : [] | [string],
          'endTime' : Time,
          'caseType' : [] | [CaseType],
          'agentName' : string,
          'taskType' : TaskType,
          'notes' : string,
          'ticketStatus' : [] | [TicketStatus],
          'escalationTransferType' : [] | [EscalationTransferType],
          'caseOrigin' : [] | [CaseOrigin],
        }
      >,
    ],
    undefined
  >,
  'createCase' : ActorMethod<
    [
      string,
      TaskType,
      [] | [CaseOrigin],
      [] | [string],
      [] | [CaseType],
      [] | [AssistanceNeeded],
      [] | [TicketStatus],
      [] | [EscalationTransferType],
      [] | [Department],
      Time,
      Time,
      string,
    ],
    undefined
  >,
  'editCase' : ActorMethod<
    [
      bigint,
      string,
      TaskType,
      [] | [CaseOrigin],
      [] | [string],
      [] | [CaseType],
      [] | [AssistanceNeeded],
      [] | [TicketStatus],
      [] | [EscalationTransferType],
      [] | [Department],
      Time,
      Time,
      string,
    ],
    undefined
  >,
  'getAllCases' : ActorMethod<[], Array<Case>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUtilizationStats' : ActorMethod<
    [Time],
    { 'daily' : [] | [bigint], 'weekly' : [] | [bigint] }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[string, string], undefined>,
  'updateUtilizationStats' : ActorMethod<[string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];