/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AssistanceNeeded = IDL.Variant({
  'no' : IDL.Null,
  'equinox' : IDL.Null,
  'onshore' : IDL.Null,
});
export const Time = IDL.Int;
export const Department = IDL.Variant({
  'cas' : IDL.Null,
  'crm' : IDL.Null,
  'csm' : IDL.Null,
  'erx' : IDL.Null,
  'lab' : IDL.Null,
  'mat' : IDL.Null,
  'psa' : IDL.Null,
  'accounting' : IDL.Null,
  'emrSupport' : IDL.Null,
  'productEnhancement' : IDL.Null,
  'pdmp' : IDL.Null,
  'billing' : IDL.Null,
  'sales' : IDL.Null,
  'clientAdvocates' : IDL.Null,
  'cleanup' : IDL.Null,
});
export const CaseType = IDL.Variant({
  'new' : IDL.Null,
  'followup' : IDL.Null,
  'reassigned' : IDL.Null,
});
export const TaskType = IDL.Variant({
  'pod' : IDL.Null,
  'clientMeeting' : IDL.Null,
  'trainingFeedbackNewTeamMember' : IDL.Null,
  'clientSideTraining' : IDL.Null,
  'supportEMRTickets' : IDL.Null,
  'feedbackReview' : IDL.Null,
  'internalTraining' : IDL.Null,
  'internalTeamMeeting' : IDL.Null,
  'trainingNewTeamMember' : IDL.Null,
  'break15' : IDL.Null,
  'break30' : IDL.Null,
});
export const TicketStatus = IDL.Variant({
  'new' : IDL.Null,
  'resolved' : IDL.Null,
  'pending' : IDL.Null,
  'escalated' : IDL.Null,
  'open' : IDL.Null,
  'transferred' : IDL.Null,
  'onHold' : IDL.Null,
});
export const EscalationTransferType = IDL.Variant({
  'na' : IDL.Null,
  'escalated' : IDL.Null,
  'transferred' : IDL.Null,
});
export const CaseOrigin = IDL.Variant({
  'chat' : IDL.Null,
  'email' : IDL.Null,
  'voiceCall' : IDL.Null,
});
export const Case = IDL.Record({
  'id' : IDL.Nat,
  'assistanceNeeded' : IDL.Opt(AssistanceNeeded),
  'startTime' : Time,
  'escalationTransferDestination' : IDL.Opt(Department),
  'emrCaseNumber' : IDL.Opt(IDL.Text),
  'endTime' : Time,
  'caseType' : IDL.Opt(CaseType),
  'agentName' : IDL.Text,
  'taskType' : TaskType,
  'notes' : IDL.Text,
  'ticketStatus' : IDL.Opt(TicketStatus),
  'escalationTransferType' : IDL.Opt(EscalationTransferType),
  'caseOrigin' : IDL.Opt(CaseOrigin),
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'shiftPreferences' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'batchCreateCases' : IDL.Func(
      [
        IDL.Vec(
          IDL.Record({
            'assistanceNeeded' : IDL.Opt(AssistanceNeeded),
            'startTime' : Time,
            'escalationTransferDestination' : IDL.Opt(Department),
            'emrCaseNumber' : IDL.Opt(IDL.Text),
            'endTime' : Time,
            'caseType' : IDL.Opt(CaseType),
            'agentName' : IDL.Text,
            'taskType' : TaskType,
            'notes' : IDL.Text,
            'ticketStatus' : IDL.Opt(TicketStatus),
            'escalationTransferType' : IDL.Opt(EscalationTransferType),
            'caseOrigin' : IDL.Opt(CaseOrigin),
          })
        ),
      ],
      [],
      [],
    ),
  'createCase' : IDL.Func(
      [
        IDL.Text,
        TaskType,
        IDL.Opt(CaseOrigin),
        IDL.Opt(IDL.Text),
        IDL.Opt(CaseType),
        IDL.Opt(AssistanceNeeded),
        IDL.Opt(TicketStatus),
        IDL.Opt(EscalationTransferType),
        IDL.Opt(Department),
        Time,
        Time,
        IDL.Text,
      ],
      [],
      [],
    ),
  'editCase' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        TaskType,
        IDL.Opt(CaseOrigin),
        IDL.Opt(IDL.Text),
        IDL.Opt(CaseType),
        IDL.Opt(AssistanceNeeded),
        IDL.Opt(TicketStatus),
        IDL.Opt(EscalationTransferType),
        IDL.Opt(Department),
        Time,
        Time,
        IDL.Text,
      ],
      [],
      [],
    ),
  'getAllCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUtilizationStats' : IDL.Func(
      [Time],
      [IDL.Record({ 'daily' : IDL.Opt(IDL.Nat), 'weekly' : IDL.Opt(IDL.Nat) })],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateUtilizationStats' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AssistanceNeeded = IDL.Variant({
    'no' : IDL.Null,
    'equinox' : IDL.Null,
    'onshore' : IDL.Null,
  });
  const Time = IDL.Int;
  const Department = IDL.Variant({
    'cas' : IDL.Null,
    'crm' : IDL.Null,
    'csm' : IDL.Null,
    'erx' : IDL.Null,
    'lab' : IDL.Null,
    'mat' : IDL.Null,
    'psa' : IDL.Null,
    'accounting' : IDL.Null,
    'emrSupport' : IDL.Null,
    'productEnhancement' : IDL.Null,
    'pdmp' : IDL.Null,
    'billing' : IDL.Null,
    'sales' : IDL.Null,
    'clientAdvocates' : IDL.Null,
    'cleanup' : IDL.Null,
  });
  const CaseType = IDL.Variant({
    'new' : IDL.Null,
    'followup' : IDL.Null,
    'reassigned' : IDL.Null,
  });
  const TaskType = IDL.Variant({
    'pod' : IDL.Null,
    'clientMeeting' : IDL.Null,
    'trainingFeedbackNewTeamMember' : IDL.Null,
    'clientSideTraining' : IDL.Null,
    'supportEMRTickets' : IDL.Null,
    'feedbackReview' : IDL.Null,
    'internalTraining' : IDL.Null,
    'internalTeamMeeting' : IDL.Null,
    'trainingNewTeamMember' : IDL.Null,
    'break15' : IDL.Null,
    'break30' : IDL.Null,
  });
  const TicketStatus = IDL.Variant({
    'new' : IDL.Null,
    'resolved' : IDL.Null,
    'pending' : IDL.Null,
    'escalated' : IDL.Null,
    'open' : IDL.Null,
    'transferred' : IDL.Null,
    'onHold' : IDL.Null,
  });
  const EscalationTransferType = IDL.Variant({
    'na' : IDL.Null,
    'escalated' : IDL.Null,
    'transferred' : IDL.Null,
  });
  const CaseOrigin = IDL.Variant({
    'chat' : IDL.Null,
    'email' : IDL.Null,
    'voiceCall' : IDL.Null,
  });
  const Case = IDL.Record({
    'id' : IDL.Nat,
    'assistanceNeeded' : IDL.Opt(AssistanceNeeded),
    'startTime' : Time,
    'escalationTransferDestination' : IDL.Opt(Department),
    'emrCaseNumber' : IDL.Opt(IDL.Text),
    'endTime' : Time,
    'caseType' : IDL.Opt(CaseType),
    'agentName' : IDL.Text,
    'taskType' : TaskType,
    'notes' : IDL.Text,
    'ticketStatus' : IDL.Opt(TicketStatus),
    'escalationTransferType' : IDL.Opt(EscalationTransferType),
    'caseOrigin' : IDL.Opt(CaseOrigin),
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'shiftPreferences' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'batchCreateCases' : IDL.Func(
        [
          IDL.Vec(
            IDL.Record({
              'assistanceNeeded' : IDL.Opt(AssistanceNeeded),
              'startTime' : Time,
              'escalationTransferDestination' : IDL.Opt(Department),
              'emrCaseNumber' : IDL.Opt(IDL.Text),
              'endTime' : Time,
              'caseType' : IDL.Opt(CaseType),
              'agentName' : IDL.Text,
              'taskType' : TaskType,
              'notes' : IDL.Text,
              'ticketStatus' : IDL.Opt(TicketStatus),
              'escalationTransferType' : IDL.Opt(EscalationTransferType),
              'caseOrigin' : IDL.Opt(CaseOrigin),
            })
          ),
        ],
        [],
        [],
      ),
    'createCase' : IDL.Func(
        [
          IDL.Text,
          TaskType,
          IDL.Opt(CaseOrigin),
          IDL.Opt(IDL.Text),
          IDL.Opt(CaseType),
          IDL.Opt(AssistanceNeeded),
          IDL.Opt(TicketStatus),
          IDL.Opt(EscalationTransferType),
          IDL.Opt(Department),
          Time,
          Time,
          IDL.Text,
        ],
        [],
        [],
      ),
    'editCase' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          TaskType,
          IDL.Opt(CaseOrigin),
          IDL.Opt(IDL.Text),
          IDL.Opt(CaseType),
          IDL.Opt(AssistanceNeeded),
          IDL.Opt(TicketStatus),
          IDL.Opt(EscalationTransferType),
          IDL.Opt(Department),
          Time,
          Time,
          IDL.Text,
        ],
        [],
        [],
      ),
    'getAllCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUtilizationStats' : IDL.Func(
        [Time],
        [
          IDL.Record({
            'daily' : IDL.Opt(IDL.Nat),
            'weekly' : IDL.Opt(IDL.Nat),
          }),
        ],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateUtilizationStats' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };