/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Case {
    id: bigint;
    assistanceNeeded?: AssistanceNeeded;
    startTime: Time;
    escalationTransferDestination?: Department;
    emrCaseNumber?: string;
    endTime: Time;
    caseType?: CaseType;
    agentName: string;
    taskType: TaskType;
    notes: string;
    ticketStatus?: TicketStatus;
    escalationTransferType?: EscalationTransferType;
    caseOrigin?: CaseOrigin;
}
export type Time = bigint;
export interface UserProfile {
    username: string;
    shiftPreferences: string;
}
export enum AssistanceNeeded {
    no = "no",
    equinox = "equinox",
    onshore = "onshore"
}
export enum CaseOrigin {
    chat = "chat",
    email = "email",
    voiceCall = "voiceCall"
}
export enum CaseType {
    new_ = "new",
    followup = "followup",
    reassigned = "reassigned"
}
export enum Department {
    cas = "cas",
    crm = "crm",
    csm = "csm",
    erx = "erx",
    lab = "lab",
    mat = "mat",
    psa = "psa",
    accounting = "accounting",
    emrSupport = "emrSupport",
    productEnhancement = "productEnhancement",
    pdmp = "pdmp",
    billing = "billing",
    sales = "sales",
    clientAdvocates = "clientAdvocates",
    cleanup = "cleanup"
}
export enum EscalationTransferType {
    na = "na",
    escalated = "escalated",
    transferred = "transferred"
}
export enum TaskType {
    pod = "pod",
    clientMeeting = "clientMeeting",
    trainingFeedbackNewTeamMember = "trainingFeedbackNewTeamMember",
    clientSideTraining = "clientSideTraining",
    supportEMRTickets = "supportEMRTickets",
    feedbackReview = "feedbackReview",
    internalTraining = "internalTraining",
    internalTeamMeeting = "internalTeamMeeting",
    trainingNewTeamMember = "trainingNewTeamMember",
    break15 = "break15",
    break30 = "break30"
}
export enum TicketStatus {
    new_ = "new",
    resolved = "resolved",
    pending = "pending",
    escalated = "escalated",
    open = "open",
    transferred = "transferred",
    onHold = "onHold"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    batchCreateCases(cases: Array<{
        assistanceNeeded?: AssistanceNeeded;
        startTime: Time;
        escalationTransferDestination?: Department;
        emrCaseNumber?: string;
        endTime: Time;
        caseType?: CaseType;
        agentName: string;
        taskType: TaskType;
        notes: string;
        ticketStatus?: TicketStatus;
        escalationTransferType?: EscalationTransferType;
        caseOrigin?: CaseOrigin;
    }>): Promise<void>;
    createCase(agentName: string, taskType: TaskType, caseOrigin: CaseOrigin | null, emrCaseNumber: string | null, caseType: CaseType | null, assistanceNeeded: AssistanceNeeded | null, ticketStatus: TicketStatus | null, escalationTransferType: EscalationTransferType | null, escalationTransferDestination: Department | null, start: Time, end: Time, notes: string): Promise<void>;
    editCase(caseId: bigint, agentName: string, taskType: TaskType, caseOrigin: CaseOrigin | null, emrCaseNumber: string | null, caseType: CaseType | null, assistanceNeeded: AssistanceNeeded | null, ticketStatus: TicketStatus | null, escalationTransferType: EscalationTransferType | null, escalationTransferDestination: Department | null, start: Time, end: Time, notes: string): Promise<void>;
    getAllCases(): Promise<Array<Case>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUtilizationStats(_period: Time): Promise<{
        daily?: bigint;
        weekly?: bigint;
    }>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(username: string, shiftPrefs: string): Promise<void>;
    updateUtilizationStats(agentName: string, workSeconds: bigint): Promise<void>;
}
import type { AssistanceNeeded as _AssistanceNeeded, Case as _Case, CaseOrigin as _CaseOrigin, CaseType as _CaseType, Department as _Department, EscalationTransferType as _EscalationTransferType, TaskType as _TaskType, TicketStatus as _TicketStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async batchCreateCases(arg0: Array<{
        assistanceNeeded?: AssistanceNeeded;
        startTime: Time;
        escalationTransferDestination?: Department;
        emrCaseNumber?: string;
        endTime: Time;
        caseType?: CaseType;
        agentName: string;
        taskType: TaskType;
        notes: string;
        ticketStatus?: TicketStatus;
        escalationTransferType?: EscalationTransferType;
        caseOrigin?: CaseOrigin;
    }>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.batchCreateCases(to_candid_vec_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.batchCreateCases(to_candid_vec_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createCase(arg0: string, arg1: TaskType, arg2: CaseOrigin | null, arg3: string | null, arg4: CaseType | null, arg5: AssistanceNeeded | null, arg6: TicketStatus | null, arg7: EscalationTransferType | null, arg8: Department | null, arg9: Time, arg10: Time, arg11: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCase(arg0, to_candid_TaskType_n11(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n20(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg8), arg9, arg10, arg11);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCase(arg0, to_candid_TaskType_n11(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n20(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg8), arg9, arg10, arg11);
            return result;
        }
    }
    async editCase(arg0: bigint, arg1: string, arg2: TaskType, arg3: CaseOrigin | null, arg4: string | null, arg5: CaseType | null, arg6: AssistanceNeeded | null, arg7: TicketStatus | null, arg8: EscalationTransferType | null, arg9: Department | null, arg10: Time, arg11: Time, arg12: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editCase(arg0, arg1, to_candid_TaskType_n11(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n20(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg9), arg10, arg11, arg12);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editCase(arg0, arg1, to_candid_TaskType_n11(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n20(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg9), arg10, arg11, arg12);
            return result;
        }
    }
    async getAllCases(): Promise<Array<Case>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCases();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCases();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUtilizationStats(arg0: Time): Promise<{
        daily?: bigint;
        weekly?: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getUtilizationStats(arg0);
                return from_candid_record_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUtilizationStats(arg0);
            return from_candid_record_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, arg1);
            return result;
        }
    }
    async updateUtilizationStats(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUtilizationStats(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUtilizationStats(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AssistanceNeeded_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssistanceNeeded): AssistanceNeeded {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_CaseOrigin_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaseOrigin): CaseOrigin {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_CaseType_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaseType): CaseType {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Case_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Case): Case {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Department_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Department): Department {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_EscalationTransferType_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EscalationTransferType): EscalationTransferType {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_TaskType_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskType): TaskType {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_TicketStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TicketStatus): TicketStatus {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AssistanceNeeded]): AssistanceNeeded | null {
    return value.length === 0 ? null : from_candid_AssistanceNeeded_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Department]): Department | null {
    return value.length === 0 ? null : from_candid_Department_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CaseType]): CaseType | null {
    return value.length === 0 ? null : from_candid_CaseType_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TicketStatus]): TicketStatus | null {
    return value.length === 0 ? null : from_candid_TicketStatus_n42(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EscalationTransferType]): EscalationTransferType | null {
    return value.length === 0 ? null : from_candid_EscalationTransferType_n45(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CaseOrigin]): CaseOrigin | null {
    return value.length === 0 ? null : from_candid_CaseOrigin_n48(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    assistanceNeeded: [] | [_AssistanceNeeded];
    startTime: _Time;
    escalationTransferDestination: [] | [_Department];
    emrCaseNumber: [] | [string];
    endTime: _Time;
    caseType: [] | [_CaseType];
    agentName: string;
    taskType: _TaskType;
    notes: string;
    ticketStatus: [] | [_TicketStatus];
    escalationTransferType: [] | [_EscalationTransferType];
    caseOrigin: [] | [_CaseOrigin];
}): {
    id: bigint;
    assistanceNeeded?: AssistanceNeeded;
    startTime: Time;
    escalationTransferDestination?: Department;
    emrCaseNumber?: string;
    endTime: Time;
    caseType?: CaseType;
    agentName: string;
    taskType: TaskType;
    notes: string;
    ticketStatus?: TicketStatus;
    escalationTransferType?: EscalationTransferType;
    caseOrigin?: CaseOrigin;
} {
    return {
        id: value.id,
        assistanceNeeded: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.assistanceNeeded)),
        startTime: value.startTime,
        escalationTransferDestination: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.escalationTransferDestination)),
        emrCaseNumber: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.emrCaseNumber)),
        endTime: value.endTime,
        caseType: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.caseType)),
        agentName: value.agentName,
        taskType: from_candid_TaskType_n39(_uploadFile, _downloadFile, value.taskType),
        notes: value.notes,
        ticketStatus: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.ticketStatus)),
        escalationTransferType: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.escalationTransferType)),
        caseOrigin: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.caseOrigin))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    daily: [] | [bigint];
    weekly: [] | [bigint];
}): {
    daily?: bigint;
    weekly?: bigint;
} {
    return {
        daily: record_opt_to_undefined(from_candid_opt_n54(_uploadFile, _downloadFile, value.daily)),
        weekly: record_opt_to_undefined(from_candid_opt_n54(_uploadFile, _downloadFile, value.weekly))
    };
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    no: null;
} | {
    equinox: null;
} | {
    onshore: null;
}): AssistanceNeeded {
    return "no" in value ? AssistanceNeeded.no : "equinox" in value ? AssistanceNeeded.equinox : "onshore" in value ? AssistanceNeeded.onshore : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cas: null;
} | {
    crm: null;
} | {
    csm: null;
} | {
    erx: null;
} | {
    lab: null;
} | {
    mat: null;
} | {
    psa: null;
} | {
    accounting: null;
} | {
    emrSupport: null;
} | {
    productEnhancement: null;
} | {
    pdmp: null;
} | {
    billing: null;
} | {
    sales: null;
} | {
    clientAdvocates: null;
} | {
    cleanup: null;
}): Department {
    return "cas" in value ? Department.cas : "crm" in value ? Department.crm : "csm" in value ? Department.csm : "erx" in value ? Department.erx : "lab" in value ? Department.lab : "mat" in value ? Department.mat : "psa" in value ? Department.psa : "accounting" in value ? Department.accounting : "emrSupport" in value ? Department.emrSupport : "productEnhancement" in value ? Department.productEnhancement : "pdmp" in value ? Department.pdmp : "billing" in value ? Department.billing : "sales" in value ? Department.sales : "clientAdvocates" in value ? Department.clientAdvocates : "cleanup" in value ? Department.cleanup : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    followup: null;
} | {
    reassigned: null;
}): CaseType {
    return "new" in value ? CaseType.new : "followup" in value ? CaseType.followup : "reassigned" in value ? CaseType.reassigned : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pod: null;
} | {
    clientMeeting: null;
} | {
    trainingFeedbackNewTeamMember: null;
} | {
    clientSideTraining: null;
} | {
    supportEMRTickets: null;
} | {
    feedbackReview: null;
} | {
    internalTraining: null;
} | {
    internalTeamMeeting: null;
} | {
    trainingNewTeamMember: null;
} | {
    break15: null;
} | {
    break30: null;
}): TaskType {
    return "pod" in value ? TaskType.pod : "clientMeeting" in value ? TaskType.clientMeeting : "trainingFeedbackNewTeamMember" in value ? TaskType.trainingFeedbackNewTeamMember : "clientSideTraining" in value ? TaskType.clientSideTraining : "supportEMRTickets" in value ? TaskType.supportEMRTickets : "feedbackReview" in value ? TaskType.feedbackReview : "internalTraining" in value ? TaskType.internalTraining : "internalTeamMeeting" in value ? TaskType.internalTeamMeeting : "trainingNewTeamMember" in value ? TaskType.trainingNewTeamMember : "break15" in value ? TaskType.break15 : "break30" in value ? TaskType.break30 : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    resolved: null;
} | {
    pending: null;
} | {
    escalated: null;
} | {
    open: null;
} | {
    transferred: null;
} | {
    onHold: null;
}): TicketStatus {
    return "new" in value ? TicketStatus.new : "resolved" in value ? TicketStatus.resolved : "pending" in value ? TicketStatus.pending : "escalated" in value ? TicketStatus.escalated : "open" in value ? TicketStatus.open : "transferred" in value ? TicketStatus.transferred : "onHold" in value ? TicketStatus.onHold : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    na: null;
} | {
    escalated: null;
} | {
    transferred: null;
}): EscalationTransferType {
    return "na" in value ? EscalationTransferType.na : "escalated" in value ? EscalationTransferType.escalated : "transferred" in value ? EscalationTransferType.transferred : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    chat: null;
} | {
    email: null;
} | {
    voiceCall: null;
}): CaseOrigin {
    return "chat" in value ? CaseOrigin.chat : "email" in value ? CaseOrigin.email : "voiceCall" in value ? CaseOrigin.voiceCall : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Case>): Array<Case> {
    return value.map((x)=>from_candid_Case_n27(_uploadFile, _downloadFile, x));
}
function to_candid_AssistanceNeeded_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssistanceNeeded): _AssistanceNeeded {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_CaseOrigin_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CaseOrigin): _CaseOrigin {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_CaseType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CaseType): _CaseType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Department_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Department): _Department {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_EscalationTransferType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EscalationTransferType): _EscalationTransferType {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_TaskType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskType): _TaskType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_TicketStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketStatus): _TicketStatus {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CaseOrigin | null): [] | [_CaseOrigin] {
    return value === null ? candid_none() : candid_some(to_candid_CaseOrigin_n17(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CaseType | null): [] | [_CaseType] {
    return value === null ? candid_none() : candid_some(to_candid_CaseType_n9(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssistanceNeeded | null): [] | [_AssistanceNeeded] {
    return value === null ? candid_none() : candid_some(to_candid_AssistanceNeeded_n5(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketStatus | null): [] | [_TicketStatus] {
    return value === null ? candid_none() : candid_some(to_candid_TicketStatus_n13(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EscalationTransferType | null): [] | [_EscalationTransferType] {
    return value === null ? candid_none() : candid_some(to_candid_EscalationTransferType_n15(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Department | null): [] | [_Department] {
    return value === null ? candid_none() : candid_some(to_candid_Department_n7(_uploadFile, _downloadFile, value));
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assistanceNeeded?: AssistanceNeeded;
    startTime: Time;
    escalationTransferDestination?: Department;
    emrCaseNumber?: string;
    endTime: Time;
    caseType?: CaseType;
    agentName: string;
    taskType: TaskType;
    notes: string;
    ticketStatus?: TicketStatus;
    escalationTransferType?: EscalationTransferType;
    caseOrigin?: CaseOrigin;
}): {
    assistanceNeeded: [] | [_AssistanceNeeded];
    startTime: _Time;
    escalationTransferDestination: [] | [_Department];
    emrCaseNumber: [] | [string];
    endTime: _Time;
    caseType: [] | [_CaseType];
    agentName: string;
    taskType: _TaskType;
    notes: string;
    ticketStatus: [] | [_TicketStatus];
    escalationTransferType: [] | [_EscalationTransferType];
    caseOrigin: [] | [_CaseOrigin];
} {
    return {
        assistanceNeeded: value.assistanceNeeded ? candid_some(to_candid_AssistanceNeeded_n5(_uploadFile, _downloadFile, value.assistanceNeeded)) : candid_none(),
        startTime: value.startTime,
        escalationTransferDestination: value.escalationTransferDestination ? candid_some(to_candid_Department_n7(_uploadFile, _downloadFile, value.escalationTransferDestination)) : candid_none(),
        emrCaseNumber: value.emrCaseNumber ? candid_some(value.emrCaseNumber) : candid_none(),
        endTime: value.endTime,
        caseType: value.caseType ? candid_some(to_candid_CaseType_n9(_uploadFile, _downloadFile, value.caseType)) : candid_none(),
        agentName: value.agentName,
        taskType: to_candid_TaskType_n11(_uploadFile, _downloadFile, value.taskType),
        notes: value.notes,
        ticketStatus: value.ticketStatus ? candid_some(to_candid_TicketStatus_n13(_uploadFile, _downloadFile, value.ticketStatus)) : candid_none(),
        escalationTransferType: value.escalationTransferType ? candid_some(to_candid_EscalationTransferType_n15(_uploadFile, _downloadFile, value.escalationTransferType)) : candid_none(),
        caseOrigin: value.caseOrigin ? candid_some(to_candid_CaseOrigin_n17(_uploadFile, _downloadFile, value.caseOrigin)) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CaseType): {
    new: null;
} | {
    followup: null;
} | {
    reassigned: null;
} {
    return value == CaseType.new ? {
        new_: null
    } : value == CaseType.followup ? {
        followup: null
    } : value == CaseType.reassigned ? {
        reassigned: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskType): {
    pod: null;
} | {
    clientMeeting: null;
} | {
    trainingFeedbackNewTeamMember: null;
} | {
    clientSideTraining: null;
} | {
    supportEMRTickets: null;
} | {
    feedbackReview: null;
} | {
    internalTraining: null;
} | {
    internalTeamMeeting: null;
} | {
    trainingNewTeamMember: null;
} | {
    break15: null;
} | {
    break30: null;
} {
    return value == TaskType.pod ? {
        pod: null
    } : value == TaskType.clientMeeting ? {
        clientMeeting: null
    } : value == TaskType.trainingFeedbackNewTeamMember ? {
        trainingFeedbackNewTeamMember: null
    } : value == TaskType.clientSideTraining ? {
        clientSideTraining: null
    } : value == TaskType.supportEMRTickets ? {
        supportEMRTickets: null
    } : value == TaskType.feedbackReview ? {
        feedbackReview: null
    } : value == TaskType.internalTraining ? {
        internalTraining: null
    } : value == TaskType.internalTeamMeeting ? {
        internalTeamMeeting: null
    } : value == TaskType.trainingNewTeamMember ? {
        trainingNewTeamMember: null
    } : value == TaskType.break15 ? {
        break15: null
    } : value == TaskType.break30 ? {
        break30: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketStatus): {
    new: null;
} | {
    resolved: null;
} | {
    pending: null;
} | {
    escalated: null;
} | {
    open: null;
} | {
    transferred: null;
} | {
    onHold: null;
} {
    return value == TicketStatus.new ? {
        new_: null
    } : value == TicketStatus.resolved ? {
        resolved: null
    } : value == TicketStatus.pending ? {
        pending: null
    } : value == TicketStatus.escalated ? {
        escalated: null
    } : value == TicketStatus.open ? {
        open: null
    } : value == TicketStatus.transferred ? {
        transferred: null
    } : value == TicketStatus.onHold ? {
        onHold: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EscalationTransferType): {
    na: null;
} | {
    escalated: null;
} | {
    transferred: null;
} {
    return value == EscalationTransferType.na ? {
        na: null
    } : value == EscalationTransferType.escalated ? {
        escalated: null
    } : value == EscalationTransferType.transferred ? {
        transferred: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CaseOrigin): {
    chat: null;
} | {
    email: null;
} | {
    voiceCall: null;
} {
    return value == CaseOrigin.chat ? {
        chat: null
    } : value == CaseOrigin.email ? {
        email: null
    } : value == CaseOrigin.voiceCall ? {
        voiceCall: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssistanceNeeded): {
    no: null;
} | {
    equinox: null;
} | {
    onshore: null;
} {
    return value == AssistanceNeeded.no ? {
        no: null
    } : value == AssistanceNeeded.equinox ? {
        equinox: null
    } : value == AssistanceNeeded.onshore ? {
        onshore: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Department): {
    cas: null;
} | {
    crm: null;
} | {
    csm: null;
} | {
    erx: null;
} | {
    lab: null;
} | {
    mat: null;
} | {
    psa: null;
} | {
    accounting: null;
} | {
    emrSupport: null;
} | {
    productEnhancement: null;
} | {
    pdmp: null;
} | {
    billing: null;
} | {
    sales: null;
} | {
    clientAdvocates: null;
} | {
    cleanup: null;
} {
    return value == Department.cas ? {
        cas: null
    } : value == Department.crm ? {
        crm: null
    } : value == Department.csm ? {
        csm: null
    } : value == Department.erx ? {
        erx: null
    } : value == Department.lab ? {
        lab: null
    } : value == Department.mat ? {
        mat: null
    } : value == Department.psa ? {
        psa: null
    } : value == Department.accounting ? {
        accounting: null
    } : value == Department.emrSupport ? {
        emrSupport: null
    } : value == Department.productEnhancement ? {
        productEnhancement: null
    } : value == Department.pdmp ? {
        pdmp: null
    } : value == Department.billing ? {
        billing: null
    } : value == Department.sales ? {
        sales: null
    } : value == Department.clientAdvocates ? {
        clientAdvocates: null
    } : value == Department.cleanup ? {
        cleanup: null
    } : value;
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    assistanceNeeded?: AssistanceNeeded;
    startTime: Time;
    escalationTransferDestination?: Department;
    emrCaseNumber?: string;
    endTime: Time;
    caseType?: CaseType;
    agentName: string;
    taskType: TaskType;
    notes: string;
    ticketStatus?: TicketStatus;
    escalationTransferType?: EscalationTransferType;
    caseOrigin?: CaseOrigin;
}>): Array<{
    assistanceNeeded: [] | [_AssistanceNeeded];
    startTime: _Time;
    escalationTransferDestination: [] | [_Department];
    emrCaseNumber: [] | [string];
    endTime: _Time;
    caseType: [] | [_CaseType];
    agentName: string;
    taskType: _TaskType;
    notes: string;
    ticketStatus: [] | [_TicketStatus];
    escalationTransferType: [] | [_EscalationTransferType];
    caseOrigin: [] | [_CaseOrigin];
}> {
    return value.map((x)=>to_candid_record_n4(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
